//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trisoft.ISHRemote.ListOfValues25ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
    [System.SerializableAttribute()]
    public partial class InfoShareFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long InfoShareErrorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XMLDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long InfoShareErrorNumber {
            get {
                return this.InfoShareErrorNumberField;
            }
            set {
                if ((this.InfoShareErrorNumberField.Equals(value) != true)) {
                    this.InfoShareErrorNumberField = value;
                    this.RaisePropertyChanged("InfoShareErrorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XMLDetail {
            get {
                return this.XMLDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.XMLDetailField, value) != true)) {
                    this.XMLDetailField = value;
                    this.RaisePropertyChanged("XMLDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityFilter", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Enumerations/API25/")]
    public enum ActivityFilter : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/", ConfigurationName="ListOfValues25ServiceReference.ListOfValues")]
    public interface ListOfValues {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/RetrieveLi" +
            "sts", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/RetrieveLi" +
            "stsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Trisoft.ISHRemote.ListOfValues25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/RetrieveLi" +
            "stsInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlLovList")]
        string RetrieveLists(string[] filterLovIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/RetrieveLi" +
            "sts", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/RetrieveLi" +
            "stsResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlLovList")]
        System.Threading.Tasks.Task<string> RetrieveListsAsync(string[] filterLovIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/RetrieveVa" +
            "lues", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/RetrieveVa" +
            "luesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Trisoft.ISHRemote.ListOfValues25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/RetrieveVa" +
            "luesInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlLovValueList")]
        string RetrieveValues(string[] lovIds, Trisoft.ISHRemote.ListOfValues25ServiceReference.ActivityFilter activityFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/RetrieveVa" +
            "lues", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/RetrieveVa" +
            "luesResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="xmlLovValueList")]
        System.Threading.Tasks.Task<string> RetrieveValuesAsync(string[] lovIds, Trisoft.ISHRemote.ListOfValues25ServiceReference.ActivityFilter activityFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/CreateValu" +
            "e", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/CreateValu" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Trisoft.ISHRemote.ListOfValues25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/CreateValu" +
            "eInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        string CreateValue(string lovId, string label, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/CreateValu" +
            "e", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/CreateValu" +
            "eResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="returnValue")]
        System.Threading.Tasks.Task<string> CreateValueAsync(string lovId, string label, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/CreateValu" +
            "e2", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/CreateValu" +
            "e2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Trisoft.ISHRemote.ListOfValues25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/CreateValu" +
            "e2InfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Response CreateValue2(Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/CreateValu" +
            "e2", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/CreateValu" +
            "e2Response")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Response> CreateValue2Async(Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/UpdateValu" +
            "e", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/UpdateValu" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Trisoft.ISHRemote.ListOfValues25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/UpdateValu" +
            "eInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        void UpdateValue(string lovId, string lovValueId, string label, string description, bool active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/UpdateValu" +
            "e", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/UpdateValu" +
            "eResponse")]
        System.Threading.Tasks.Task UpdateValueAsync(string lovId, string lovValueId, string label, string description, bool active);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/DeleteValu" +
            "e", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/DeleteValu" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Trisoft.ISHRemote.ListOfValues25ServiceReference.InfoShareFault), Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/DeleteValu" +
            "eInfoShareFault", Name="InfoShareFault", Namespace="http://sdl.com/trisoft/2012/06/WebServices/Contracts/Faults/API25/")]
        void DeleteValue(string lovId, string lovValueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/DeleteValu" +
            "e", ReplyAction="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/ListOfValues/DeleteValu" +
            "eResponse")]
        System.Threading.Tasks.Task DeleteValueAsync(string lovId, string lovValueId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateValue2", WrapperNamespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/", IsWrapped=true)]
    public partial class CreateValue2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/", Order=0)]
        public string lovId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/", Order=1)]
        public string lovValueId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/", Order=2)]
        public string label;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/", Order=3)]
        public string description;
        
        public CreateValue2Request() {
        }
        
        public CreateValue2Request(string lovId, string lovValueId, string label, string description) {
            this.lovId = lovId;
            this.lovValueId = lovValueId;
            this.label = label;
            this.description = description;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateValue2Response", WrapperNamespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/", IsWrapped=true)]
    public partial class CreateValue2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdl.com/trisoft/2012/06/WebServices/Services/API25/", Order=0)]
        public string lovValueId;
        
        public CreateValue2Response() {
        }
        
        public CreateValue2Response(string lovValueId) {
            this.lovValueId = lovValueId;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ListOfValuesChannel : Trisoft.ISHRemote.ListOfValues25ServiceReference.ListOfValues, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListOfValuesClient : System.ServiceModel.ClientBase<Trisoft.ISHRemote.ListOfValues25ServiceReference.ListOfValues>, Trisoft.ISHRemote.ListOfValues25ServiceReference.ListOfValues {
        
        public ListOfValuesClient() {
        }
        
        public ListOfValuesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListOfValuesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListOfValuesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListOfValuesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RetrieveLists(string[] filterLovIds) {
            return base.Channel.RetrieveLists(filterLovIds);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveListsAsync(string[] filterLovIds) {
            return base.Channel.RetrieveListsAsync(filterLovIds);
        }
        
        public string RetrieveValues(string[] lovIds, Trisoft.ISHRemote.ListOfValues25ServiceReference.ActivityFilter activityFilter) {
            return base.Channel.RetrieveValues(lovIds, activityFilter);
        }
        
        public System.Threading.Tasks.Task<string> RetrieveValuesAsync(string[] lovIds, Trisoft.ISHRemote.ListOfValues25ServiceReference.ActivityFilter activityFilter) {
            return base.Channel.RetrieveValuesAsync(lovIds, activityFilter);
        }
        
        public string CreateValue(string lovId, string label, string description) {
            return base.Channel.CreateValue(lovId, label, description);
        }
        
        public System.Threading.Tasks.Task<string> CreateValueAsync(string lovId, string label, string description) {
            return base.Channel.CreateValueAsync(lovId, label, description);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Response Trisoft.ISHRemote.ListOfValues25ServiceReference.ListOfValues.CreateValue2(Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Request request) {
            return base.Channel.CreateValue2(request);
        }
        
        public void CreateValue2(string lovId, ref string lovValueId, string label, string description) {
            Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Request inValue = new Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Request();
            inValue.lovId = lovId;
            inValue.lovValueId = lovValueId;
            inValue.label = label;
            inValue.description = description;
            Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Response retVal = ((Trisoft.ISHRemote.ListOfValues25ServiceReference.ListOfValues)(this)).CreateValue2(inValue);
            lovValueId = retVal.lovValueId;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Response> CreateValue2Async(Trisoft.ISHRemote.ListOfValues25ServiceReference.CreateValue2Request request) {
            return base.Channel.CreateValue2Async(request);
        }
        
        public void UpdateValue(string lovId, string lovValueId, string label, string description, bool active) {
            base.Channel.UpdateValue(lovId, lovValueId, label, description, active);
        }
        
        public System.Threading.Tasks.Task UpdateValueAsync(string lovId, string lovValueId, string label, string description, bool active) {
            return base.Channel.UpdateValueAsync(lovId, lovValueId, label, description, active);
        }
        
        public void DeleteValue(string lovId, string lovValueId) {
            base.Channel.DeleteValue(lovId, lovValueId);
        }
        
        public System.Threading.Tasks.Task DeleteValueAsync(string lovId, string lovValueId) {
            return base.Channel.DeleteValueAsync(lovId, lovValueId);
        }
    }
}
