//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trisoft.ISHRemote.OutputFormat25ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", ConfigurationName="Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap")]
    public interface OutputFormat25Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/GetMetaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataResponse GetMetaData(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/GetMetaData", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataResponse> GetMetaDataAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/RetrieveMetaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataResponse RetrieveMetaData(Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/RetrieveMetaData", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataResponse> RetrieveMetaDataAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/GetOutputFormatId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdResponse GetOutputFormatId(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/GetOutputFormatId", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdResponse> GetOutputFormatIdAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/GetOutputFormatName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameResponse GetOutputFormatName(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/GetOutputFormatName", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameResponse> GetOutputFormatNameAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/Find", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.FindResponse Find(Trisoft.ISHRemote.OutputFormat25ServiceReference.FindRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.FindResponse> FindAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateResponse Create(Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateResponse> CreateAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateResponse Update(Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateResponse> UpdateAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteResponse Delete(Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteResponse> DeleteAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMetaData", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class GetMetaDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psOutputFormatId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psXMLRequestedMetadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=3)]
        public string psOutXMLObjList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=4)]
        public string psOutOutputEDT;
        
        public GetMetaDataRequest()
        {
        }
        
        public GetMetaDataRequest(string psAuthContext, string psOutputFormatId, string psXMLRequestedMetadata, string psOutXMLObjList, string psOutOutputEDT)
        {
            this.psAuthContext = psAuthContext;
            this.psOutputFormatId = psOutputFormatId;
            this.psXMLRequestedMetadata = psXMLRequestedMetadata;
            this.psOutXMLObjList = psOutXMLObjList;
            this.psOutOutputEDT = psOutOutputEDT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMetaDataResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class GetMetaDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string GetMetaDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psOutXMLObjList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=3)]
        public string psOutOutputEDT;
        
        public GetMetaDataResponse()
        {
        }
        
        public GetMetaDataResponse(string GetMetaDataResult, string psAuthContext, string psOutXMLObjList, string psOutOutputEDT)
        {
            this.GetMetaDataResult = GetMetaDataResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
            this.psOutOutputEDT = psOutOutputEDT;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5")]
    public enum eActivityFilter
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Inactive,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveMetaData", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class RetrieveMetaDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string[] pasOutputFormatIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public Trisoft.ISHRemote.OutputFormat25ServiceReference.eActivityFilter peActivityFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=3)]
        public string psXMLMetadataFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=4)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=5)]
        public string psOutXMLObjList;
        
        public RetrieveMetaDataRequest()
        {
        }
        
        public RetrieveMetaDataRequest(string psAuthContext, string[] pasOutputFormatIds, Trisoft.ISHRemote.OutputFormat25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.pasOutputFormatIds = pasOutputFormatIds;
            this.peActivityFilter = peActivityFilter;
            this.psXMLMetadataFilter = psXMLMetadataFilter;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveMetaDataResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class RetrieveMetaDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string RetrieveMetaDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public RetrieveMetaDataResponse()
        {
        }
        
        public RetrieveMetaDataResponse(string RetrieveMetaDataResult, string psAuthContext, string psOutXMLObjList)
        {
            this.RetrieveMetaDataResult = RetrieveMetaDataResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOutputFormatId", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class GetOutputFormatIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psOutputFormatName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psOutOutputFormatId;
        
        public GetOutputFormatIdRequest()
        {
        }
        
        public GetOutputFormatIdRequest(string psAuthContext, string psOutputFormatName, string psOutOutputFormatId)
        {
            this.psAuthContext = psAuthContext;
            this.psOutputFormatName = psOutputFormatName;
            this.psOutOutputFormatId = psOutOutputFormatId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOutputFormatIdResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class GetOutputFormatIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string GetOutputFormatIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psOutOutputFormatId;
        
        public GetOutputFormatIdResponse()
        {
        }
        
        public GetOutputFormatIdResponse(string GetOutputFormatIdResult, string psAuthContext, string psOutOutputFormatId)
        {
            this.GetOutputFormatIdResult = GetOutputFormatIdResult;
            this.psAuthContext = psAuthContext;
            this.psOutOutputFormatId = psOutOutputFormatId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOutputFormatName", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class GetOutputFormatNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psOutputFormatId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psOutOutputFormatName;
        
        public GetOutputFormatNameRequest()
        {
        }
        
        public GetOutputFormatNameRequest(string psAuthContext, string psOutputFormatId, string psOutOutputFormatName)
        {
            this.psAuthContext = psAuthContext;
            this.psOutputFormatId = psOutputFormatId;
            this.psOutOutputFormatName = psOutOutputFormatName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOutputFormatNameResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class GetOutputFormatNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string GetOutputFormatNameResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psOutOutputFormatName;
        
        public GetOutputFormatNameResponse()
        {
        }
        
        public GetOutputFormatNameResponse(string GetOutputFormatNameResult, string psAuthContext, string psOutOutputFormatName)
        {
            this.GetOutputFormatNameResult = GetOutputFormatNameResult;
            this.psAuthContext = psAuthContext;
            this.psOutOutputFormatName = psOutOutputFormatName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Find", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class FindRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public Trisoft.ISHRemote.OutputFormat25ServiceReference.eActivityFilter peActivityFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psXMLMetadataFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=3)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=4)]
        public string psOutXMLObjList;
        
        public FindRequest()
        {
        }
        
        public FindRequest(string psAuthContext, Trisoft.ISHRemote.OutputFormat25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.peActivityFilter = peActivityFilter;
            this.psXMLMetadataFilter = psXMLMetadataFilter;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class FindResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string FindResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public FindResponse()
        {
        }
        
        public FindResponse(string FindResult, string psAuthContext, string psOutXMLObjList)
        {
            this.FindResult = FindResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class CreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psOutputFormatName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psOutputEDT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=3)]
        public string psXMLMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=4)]
        public string psOutOutputFormatId;
        
        public CreateRequest()
        {
        }
        
        public CreateRequest(string psAuthContext, string psOutputFormatName, string psOutputEDT, string psXMLMetaData, string psOutOutputFormatId)
        {
            this.psAuthContext = psAuthContext;
            this.psOutputFormatName = psOutputFormatName;
            this.psOutputEDT = psOutputEDT;
            this.psXMLMetaData = psXMLMetaData;
            this.psOutOutputFormatId = psOutOutputFormatId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class CreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string CreateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psOutOutputFormatId;
        
        public CreateResponse()
        {
        }
        
        public CreateResponse(string CreateResult, string psAuthContext, string psOutOutputFormatId)
        {
            this.CreateResult = CreateResult;
            this.psAuthContext = psAuthContext;
            this.psOutOutputFormatId = psOutOutputFormatId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psOutputFormatId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=2)]
        public string psOutputEDT;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=3)]
        public string psXMLMetaData;
        
        public UpdateRequest()
        {
        }
        
        public UpdateRequest(string psAuthContext, string psOutputFormatId, string psOutputEDT, string psXMLMetaData)
        {
            this.psAuthContext = psAuthContext;
            this.psOutputFormatId = psOutputFormatId;
            this.psOutputEDT = psOutputEDT;
            this.psXMLMetaData = psXMLMetaData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string UpdateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psAuthContext;
        
        public UpdateResponse()
        {
        }
        
        public UpdateResponse(string UpdateResult, string psAuthContext)
        {
            this.UpdateResult = UpdateResult;
            this.psAuthContext = psAuthContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class DeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psOutputFormatId;
        
        public DeleteRequest()
        {
        }
        
        public DeleteRequest(string psAuthContext, string psOutputFormatId)
        {
            this.psAuthContext = psAuthContext;
            this.psOutputFormatId = psOutputFormatId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", IsWrapped=true)]
    public partial class DeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=0)]
        public string DeleteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:OutputFormat:2.5", Order=1)]
        public string psAuthContext;
        
        public DeleteResponse()
        {
        }
        
        public DeleteResponse(string DeleteResult, string psAuthContext)
        {
            this.DeleteResult = DeleteResult;
            this.psAuthContext = psAuthContext;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface OutputFormat25SoapChannel : Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OutputFormat25SoapClient : System.ServiceModel.ClientBase<Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap>, Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OutputFormat25SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(OutputFormat25SoapClient.GetBindingForEndpoint(endpointConfiguration), OutputFormat25SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OutputFormat25SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OutputFormat25SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OutputFormat25SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OutputFormat25SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OutputFormat25SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataResponse Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap.GetMetaData(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataRequest request)
        {
            return base.Channel.GetMetaData(request);
        }
        
        public string GetMetaData(ref string psAuthContext, string psOutputFormatId, string psXMLRequestedMetadata, ref string psOutXMLObjList, ref string psOutOutputEDT)
        {
            Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataRequest inValue = new Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psOutputFormatId = psOutputFormatId;
            inValue.psXMLRequestedMetadata = psXMLRequestedMetadata;
            inValue.psOutXMLObjList = psOutXMLObjList;
            inValue.psOutOutputEDT = psOutOutputEDT;
            Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataResponse retVal = ((Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap)(this)).GetMetaData(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            psOutOutputEDT = retVal.psOutOutputEDT;
            return retVal.GetMetaDataResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataResponse> GetMetaDataAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetMetaDataRequest request)
        {
            return base.Channel.GetMetaDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataResponse Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap.RetrieveMetaData(Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataRequest request)
        {
            return base.Channel.RetrieveMetaData(request);
        }
        
        public string RetrieveMetaData(ref string psAuthContext, string[] pasOutputFormatIds, Trisoft.ISHRemote.OutputFormat25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataRequest inValue = new Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.pasOutputFormatIds = pasOutputFormatIds;
            inValue.peActivityFilter = peActivityFilter;
            inValue.psXMLMetadataFilter = psXMLMetadataFilter;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataResponse retVal = ((Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap)(this)).RetrieveMetaData(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.RetrieveMetaDataResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataResponse> RetrieveMetaDataAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.RetrieveMetaDataRequest request)
        {
            return base.Channel.RetrieveMetaDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdResponse Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap.GetOutputFormatId(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdRequest request)
        {
            return base.Channel.GetOutputFormatId(request);
        }
        
        public string GetOutputFormatId(ref string psAuthContext, string psOutputFormatName, ref string psOutOutputFormatId)
        {
            Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdRequest inValue = new Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psOutputFormatName = psOutputFormatName;
            inValue.psOutOutputFormatId = psOutOutputFormatId;
            Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdResponse retVal = ((Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap)(this)).GetOutputFormatId(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutOutputFormatId = retVal.psOutOutputFormatId;
            return retVal.GetOutputFormatIdResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdResponse> GetOutputFormatIdAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatIdRequest request)
        {
            return base.Channel.GetOutputFormatIdAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameResponse Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap.GetOutputFormatName(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameRequest request)
        {
            return base.Channel.GetOutputFormatName(request);
        }
        
        public string GetOutputFormatName(ref string psAuthContext, string psOutputFormatId, ref string psOutOutputFormatName)
        {
            Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameRequest inValue = new Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psOutputFormatId = psOutputFormatId;
            inValue.psOutOutputFormatName = psOutOutputFormatName;
            Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameResponse retVal = ((Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap)(this)).GetOutputFormatName(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutOutputFormatName = retVal.psOutOutputFormatName;
            return retVal.GetOutputFormatNameResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameResponse> GetOutputFormatNameAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.GetOutputFormatNameRequest request)
        {
            return base.Channel.GetOutputFormatNameAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.FindResponse Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap.Find(Trisoft.ISHRemote.OutputFormat25ServiceReference.FindRequest request)
        {
            return base.Channel.Find(request);
        }
        
        public string Find(ref string psAuthContext, Trisoft.ISHRemote.OutputFormat25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.OutputFormat25ServiceReference.FindRequest inValue = new Trisoft.ISHRemote.OutputFormat25ServiceReference.FindRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.peActivityFilter = peActivityFilter;
            inValue.psXMLMetadataFilter = psXMLMetadataFilter;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.OutputFormat25ServiceReference.FindResponse retVal = ((Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap)(this)).Find(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.FindResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.FindResponse> FindAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.FindRequest request)
        {
            return base.Channel.FindAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateResponse Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap.Create(Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateRequest request)
        {
            return base.Channel.Create(request);
        }
        
        public string Create(ref string psAuthContext, string psOutputFormatName, string psOutputEDT, string psXMLMetaData, ref string psOutOutputFormatId)
        {
            Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateRequest inValue = new Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psOutputFormatName = psOutputFormatName;
            inValue.psOutputEDT = psOutputEDT;
            inValue.psXMLMetaData = psXMLMetaData;
            inValue.psOutOutputFormatId = psOutOutputFormatId;
            Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateResponse retVal = ((Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap)(this)).Create(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutOutputFormatId = retVal.psOutOutputFormatId;
            return retVal.CreateResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateResponse> CreateAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.CreateRequest request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateResponse Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap.Update(Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateRequest request)
        {
            return base.Channel.Update(request);
        }
        
        public string Update(ref string psAuthContext, string psOutputFormatId, string psOutputEDT, string psXMLMetaData)
        {
            Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateRequest inValue = new Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psOutputFormatId = psOutputFormatId;
            inValue.psOutputEDT = psOutputEDT;
            inValue.psXMLMetaData = psXMLMetaData;
            Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateResponse retVal = ((Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap)(this)).Update(inValue);
            psAuthContext = retVal.psAuthContext;
            return retVal.UpdateResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateResponse> UpdateAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.UpdateRequest request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteResponse Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap.Delete(Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteRequest request)
        {
            return base.Channel.Delete(request);
        }
        
        public string Delete(ref string psAuthContext, string psOutputFormatId)
        {
            Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteRequest inValue = new Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psOutputFormatId = psOutputFormatId;
            Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteResponse retVal = ((Trisoft.ISHRemote.OutputFormat25ServiceReference.OutputFormat25Soap)(this)).Delete(inValue);
            psAuthContext = retVal.psAuthContext;
            return retVal.DeleteResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteResponse> DeleteAsync(Trisoft.ISHRemote.OutputFormat25ServiceReference.DeleteRequest request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OutputFormat25Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OutputFormat25Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OutputFormat25Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://ish.example.com/ISHWS/outputformat25.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.OutputFormat25Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ish.example.com/ISHWS/outputformat25.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            OutputFormat25Soap,
            
            OutputFormat25Soap12,
        }
    }
}

