//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trisoft.ISHRemote.User25ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", ConfigurationName="Trisoft.ISHRemote.User25ServiceReference.User25Soap")]
    public interface User25Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/GetMetaDataByIshUserRef", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefResponse GetMetaDataByIshUserRef(Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/GetMetaDataByIshUserRef", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefResponse> GetMetaDataByIshUserRefAsync(Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/GetMetaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.GetMetaDataResponse GetMetaData(Trisoft.ISHRemote.User25ServiceReference.GetMetaDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/GetMetaData", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.GetMetaDataResponse> GetMetaDataAsync(Trisoft.ISHRemote.User25ServiceReference.GetMetaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/GetMyMetaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataResponse GetMyMetaData(Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/GetMyMetaData", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataResponse> GetMyMetaDataAsync(Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/RetrieveMetaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataResponse RetrieveMetaData(Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/RetrieveMetaData", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataResponse> RetrieveMetaDataAsync(Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/RetrieveMetaDataByIshUserRefs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsResponse RetrieveMetaDataByIshUserRefs(Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/RetrieveMetaDataByIshUserRefs", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsResponse> RetrieveMetaDataByIshUserRefsAsync(Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/Find", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.FindResponse Find(Trisoft.ISHRemote.User25ServiceReference.FindRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.FindResponse> FindAsync(Trisoft.ISHRemote.User25ServiceReference.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.CreateResponse Create(Trisoft.ISHRemote.User25ServiceReference.CreateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.CreateResponse> CreateAsync(Trisoft.ISHRemote.User25ServiceReference.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.UpdateResponse Update(Trisoft.ISHRemote.User25ServiceReference.UpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.UpdateResponse> UpdateAsync(Trisoft.ISHRemote.User25ServiceReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.DeleteResponse Delete(Trisoft.ISHRemote.User25ServiceReference.DeleteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.DeleteResponse> DeleteAsync(Trisoft.ISHRemote.User25ServiceReference.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChangePassword(string psApplicationName, string psUserName, string psOldPassword, string psNewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ChangePasswordAsync(string psApplicationName, string psUserName, string psOldPassword, string psNewPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/SetPreferences", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.SetPreferencesResponse SetPreferences(Trisoft.ISHRemote.User25ServiceReference.SetPreferencesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/SetPreferences", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.SetPreferencesResponse> SetPreferencesAsync(Trisoft.ISHRemote.User25ServiceReference.SetPreferencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/RetrievePreferences", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesResponse RetrievePreferences(Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/RetrievePreferences", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesResponse> RetrievePreferencesAsync(Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/FindPreferences", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.FindPreferencesResponse FindPreferences(Trisoft.ISHRemote.User25ServiceReference.FindPreferencesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/FindPreferences", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.FindPreferencesResponse> FindPreferencesAsync(Trisoft.ISHRemote.User25ServiceReference.FindPreferencesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/DeletePreference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceResponse DeletePreference(Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:User:2.5/DeletePreference", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceResponse> DeletePreferenceAsync(Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMetaDataByIshUserRef", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class GetMetaDataByIshUserRefRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public long plUserRef;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=3)]
        public string psOutXMLObjList;
        
        public GetMetaDataByIshUserRefRequest()
        {
        }
        
        public GetMetaDataByIshUserRefRequest(string psAuthContext, long plUserRef, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.plUserRef = plUserRef;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMetaDataByIshUserRefResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class GetMetaDataByIshUserRefResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string GetMetaDataByIshUserRefResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public GetMetaDataByIshUserRefResponse()
        {
        }
        
        public GetMetaDataByIshUserRefResponse(string GetMetaDataByIshUserRefResult, string psAuthContext, string psOutXMLObjList)
        {
            this.GetMetaDataByIshUserRefResult = GetMetaDataByIshUserRefResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMetaData", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class GetMetaDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=3)]
        public string psOutXMLObjList;
        
        public GetMetaDataRequest()
        {
        }
        
        public GetMetaDataRequest(string psAuthContext, string psUserId, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.psUserId = psUserId;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMetaDataResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class GetMetaDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string GetMetaDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public GetMetaDataResponse()
        {
        }
        
        public GetMetaDataResponse(string GetMetaDataResult, string psAuthContext, string psOutXMLObjList)
        {
            this.GetMetaDataResult = GetMetaDataResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMyMetaData", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class GetMyMetaDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public GetMyMetaDataRequest()
        {
        }
        
        public GetMyMetaDataRequest(string psAuthContext, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMyMetaDataResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class GetMyMetaDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string GetMyMetaDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public GetMyMetaDataResponse()
        {
        }
        
        public GetMyMetaDataResponse(string GetMyMetaDataResult, string psAuthContext, string psOutXMLObjList)
        {
            this.GetMyMetaDataResult = GetMyMetaDataResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5")]
    public enum eActivityFilter
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Inactive,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveMetaData", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class RetrieveMetaDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string[] pasUserIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public Trisoft.ISHRemote.User25ServiceReference.eActivityFilter peActivityFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=3)]
        public string psXMLMetadataFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=4)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=5)]
        public string psOutXMLObjList;
        
        public RetrieveMetaDataRequest()
        {
        }
        
        public RetrieveMetaDataRequest(string psAuthContext, string[] pasUserIds, Trisoft.ISHRemote.User25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.pasUserIds = pasUserIds;
            this.peActivityFilter = peActivityFilter;
            this.psXMLMetadataFilter = psXMLMetadataFilter;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveMetaDataResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class RetrieveMetaDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string RetrieveMetaDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public RetrieveMetaDataResponse()
        {
        }
        
        public RetrieveMetaDataResponse(string RetrieveMetaDataResult, string psAuthContext, string psOutXMLObjList)
        {
            this.RetrieveMetaDataResult = RetrieveMetaDataResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveMetaDataByIshUserRefs", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class RetrieveMetaDataByIshUserRefsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public long[] palUserRefs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public Trisoft.ISHRemote.User25ServiceReference.eActivityFilter peActivityFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=3)]
        public string psXMLMetadataFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=4)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=5)]
        public string psOutXMLObjList;
        
        public RetrieveMetaDataByIshUserRefsRequest()
        {
        }
        
        public RetrieveMetaDataByIshUserRefsRequest(string psAuthContext, long[] palUserRefs, Trisoft.ISHRemote.User25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.palUserRefs = palUserRefs;
            this.peActivityFilter = peActivityFilter;
            this.psXMLMetadataFilter = psXMLMetadataFilter;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveMetaDataByIshUserRefsResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class RetrieveMetaDataByIshUserRefsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string RetrieveMetaDataByIshUserRefsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public RetrieveMetaDataByIshUserRefsResponse()
        {
        }
        
        public RetrieveMetaDataByIshUserRefsResponse(string RetrieveMetaDataByIshUserRefsResult, string psAuthContext, string psOutXMLObjList)
        {
            this.RetrieveMetaDataByIshUserRefsResult = RetrieveMetaDataByIshUserRefsResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Find", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class FindRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public Trisoft.ISHRemote.User25ServiceReference.eActivityFilter peActivityFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psXMLMetadataFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=3)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=4)]
        public string psOutXMLObjList;
        
        public FindRequest()
        {
        }
        
        public FindRequest(string psAuthContext, Trisoft.ISHRemote.User25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.peActivityFilter = peActivityFilter;
            this.psXMLMetadataFilter = psXMLMetadataFilter;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class FindResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string FindResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public FindResponse()
        {
        }
        
        public FindResponse(string FindResult, string psAuthContext, string psOutXMLObjList)
        {
            this.FindResult = FindResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class CreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psXMLMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=3)]
        public string psOutUserId;
        
        public CreateRequest()
        {
        }
        
        public CreateRequest(string psAuthContext, string psUserName, string psXMLMetaData, string psOutUserId)
        {
            this.psAuthContext = psAuthContext;
            this.psUserName = psUserName;
            this.psXMLMetaData = psXMLMetaData;
            this.psOutUserId = psOutUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class CreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string CreateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psOutUserId;
        
        public CreateResponse()
        {
        }
        
        public CreateResponse(string CreateResult, string psAuthContext, string psOutUserId)
        {
            this.CreateResult = CreateResult;
            this.psAuthContext = psAuthContext;
            this.psOutUserId = psOutUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psXMLMetaData;
        
        public UpdateRequest()
        {
        }
        
        public UpdateRequest(string psAuthContext, string psUserId, string psXMLMetaData)
        {
            this.psAuthContext = psAuthContext;
            this.psUserId = psUserId;
            this.psXMLMetaData = psXMLMetaData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string UpdateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        public UpdateResponse()
        {
        }
        
        public UpdateResponse(string UpdateResult, string psAuthContext)
        {
            this.UpdateResult = UpdateResult;
            this.psAuthContext = psAuthContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class DeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psUserId;
        
        public DeleteRequest()
        {
        }
        
        public DeleteRequest(string psAuthContext, string psUserId)
        {
            this.psAuthContext = psAuthContext;
            this.psUserId = psUserId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class DeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string DeleteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        public DeleteResponse()
        {
        }
        
        public DeleteResponse(string DeleteResult, string psAuthContext)
        {
            this.DeleteResult = DeleteResult;
            this.psAuthContext = psAuthContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPreferences", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class SetPreferencesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psXMLPreferences;
        
        public SetPreferencesRequest()
        {
        }
        
        public SetPreferencesRequest(string psAuthContext, string psUserId, string psXMLPreferences)
        {
            this.psAuthContext = psAuthContext;
            this.psUserId = psUserId;
            this.psXMLPreferences = psXMLPreferences;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetPreferencesResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class SetPreferencesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string SetPreferencesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        public SetPreferencesResponse()
        {
        }
        
        public SetPreferencesResponse(string SetPreferencesResult, string psAuthContext)
        {
            this.SetPreferencesResult = SetPreferencesResult;
            this.psAuthContext = psAuthContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrievePreferences", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class RetrievePreferencesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string[] pasSetNames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=3)]
        public string psOutXMLPreferences;
        
        public RetrievePreferencesRequest()
        {
        }
        
        public RetrievePreferencesRequest(string psAuthContext, string psUserId, string[] pasSetNames, string psOutXMLPreferences)
        {
            this.psAuthContext = psAuthContext;
            this.psUserId = psUserId;
            this.pasSetNames = pasSetNames;
            this.psOutXMLPreferences = psOutXMLPreferences;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrievePreferencesResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class RetrievePreferencesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string RetrievePreferencesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psOutXMLPreferences;
        
        public RetrievePreferencesResponse()
        {
        }
        
        public RetrievePreferencesResponse(string RetrievePreferencesResult, string psAuthContext, string psOutXMLPreferences)
        {
            this.RetrievePreferencesResult = RetrievePreferencesResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLPreferences = psOutXMLPreferences;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindPreferences", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class FindPreferencesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psSetNameFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=3)]
        public string psItemNameFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=4)]
        public string psOutXMLPreferences;
        
        public FindPreferencesRequest()
        {
        }
        
        public FindPreferencesRequest(string psAuthContext, string psUserId, string psSetNameFilter, string psItemNameFilter, string psOutXMLPreferences)
        {
            this.psAuthContext = psAuthContext;
            this.psUserId = psUserId;
            this.psSetNameFilter = psSetNameFilter;
            this.psItemNameFilter = psItemNameFilter;
            this.psOutXMLPreferences = psOutXMLPreferences;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindPreferencesResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class FindPreferencesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string FindPreferencesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psOutXMLPreferences;
        
        public FindPreferencesResponse()
        {
        }
        
        public FindPreferencesResponse(string FindPreferencesResult, string psAuthContext, string psOutXMLPreferences)
        {
            this.FindPreferencesResult = FindPreferencesResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLPreferences = psOutXMLPreferences;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePreference", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class DeletePreferenceRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psUserId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=2)]
        public string psSetName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=3)]
        public string psItemName;
        
        public DeletePreferenceRequest()
        {
        }
        
        public DeletePreferenceRequest(string psAuthContext, string psUserId, string psSetName, string psItemName)
        {
            this.psAuthContext = psAuthContext;
            this.psUserId = psUserId;
            this.psSetName = psSetName;
            this.psItemName = psItemName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeletePreferenceResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", IsWrapped=true)]
    public partial class DeletePreferenceResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=0)]
        public string DeletePreferenceResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:User:2.5", Order=1)]
        public string psAuthContext;
        
        public DeletePreferenceResponse()
        {
        }
        
        public DeletePreferenceResponse(string DeletePreferenceResult, string psAuthContext)
        {
            this.DeletePreferenceResult = DeletePreferenceResult;
            this.psAuthContext = psAuthContext;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface User25SoapChannel : Trisoft.ISHRemote.User25ServiceReference.User25Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class User25SoapClient : System.ServiceModel.ClientBase<Trisoft.ISHRemote.User25ServiceReference.User25Soap>, Trisoft.ISHRemote.User25ServiceReference.User25Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public User25SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(User25SoapClient.GetBindingForEndpoint(endpointConfiguration), User25SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public User25SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(User25SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public User25SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(User25SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public User25SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.GetMetaDataByIshUserRef(Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefRequest request)
        {
            return base.Channel.GetMetaDataByIshUserRef(request);
        }
        
        public string GetMetaDataByIshUserRef(ref string psAuthContext, long plUserRef, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.plUserRef = plUserRef;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).GetMetaDataByIshUserRef(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.GetMetaDataByIshUserRefResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefResponse> GetMetaDataByIshUserRefAsync(Trisoft.ISHRemote.User25ServiceReference.GetMetaDataByIshUserRefRequest request)
        {
            return base.Channel.GetMetaDataByIshUserRefAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.GetMetaDataResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.GetMetaData(Trisoft.ISHRemote.User25ServiceReference.GetMetaDataRequest request)
        {
            return base.Channel.GetMetaData(request);
        }
        
        public string GetMetaData(ref string psAuthContext, string psUserId, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.User25ServiceReference.GetMetaDataRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.GetMetaDataRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserId = psUserId;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.User25ServiceReference.GetMetaDataResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).GetMetaData(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.GetMetaDataResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.GetMetaDataResponse> GetMetaDataAsync(Trisoft.ISHRemote.User25ServiceReference.GetMetaDataRequest request)
        {
            return base.Channel.GetMetaDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.GetMyMetaData(Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataRequest request)
        {
            return base.Channel.GetMyMetaData(request);
        }
        
        public string GetMyMetaData(ref string psAuthContext, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).GetMyMetaData(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.GetMyMetaDataResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataResponse> GetMyMetaDataAsync(Trisoft.ISHRemote.User25ServiceReference.GetMyMetaDataRequest request)
        {
            return base.Channel.GetMyMetaDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.RetrieveMetaData(Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataRequest request)
        {
            return base.Channel.RetrieveMetaData(request);
        }
        
        public string RetrieveMetaData(ref string psAuthContext, string[] pasUserIds, Trisoft.ISHRemote.User25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.pasUserIds = pasUserIds;
            inValue.peActivityFilter = peActivityFilter;
            inValue.psXMLMetadataFilter = psXMLMetadataFilter;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).RetrieveMetaData(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.RetrieveMetaDataResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataResponse> RetrieveMetaDataAsync(Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataRequest request)
        {
            return base.Channel.RetrieveMetaDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.RetrieveMetaDataByIshUserRefs(Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsRequest request)
        {
            return base.Channel.RetrieveMetaDataByIshUserRefs(request);
        }
        
        public string RetrieveMetaDataByIshUserRefs(ref string psAuthContext, long[] palUserRefs, Trisoft.ISHRemote.User25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.palUserRefs = palUserRefs;
            inValue.peActivityFilter = peActivityFilter;
            inValue.psXMLMetadataFilter = psXMLMetadataFilter;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).RetrieveMetaDataByIshUserRefs(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.RetrieveMetaDataByIshUserRefsResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsResponse> RetrieveMetaDataByIshUserRefsAsync(Trisoft.ISHRemote.User25ServiceReference.RetrieveMetaDataByIshUserRefsRequest request)
        {
            return base.Channel.RetrieveMetaDataByIshUserRefsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.FindResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.Find(Trisoft.ISHRemote.User25ServiceReference.FindRequest request)
        {
            return base.Channel.Find(request);
        }
        
        public string Find(ref string psAuthContext, Trisoft.ISHRemote.User25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.User25ServiceReference.FindRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.FindRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.peActivityFilter = peActivityFilter;
            inValue.psXMLMetadataFilter = psXMLMetadataFilter;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.User25ServiceReference.FindResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).Find(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.FindResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.FindResponse> FindAsync(Trisoft.ISHRemote.User25ServiceReference.FindRequest request)
        {
            return base.Channel.FindAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.CreateResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.Create(Trisoft.ISHRemote.User25ServiceReference.CreateRequest request)
        {
            return base.Channel.Create(request);
        }
        
        public string Create(ref string psAuthContext, string psUserName, string psXMLMetaData, ref string psOutUserId)
        {
            Trisoft.ISHRemote.User25ServiceReference.CreateRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.CreateRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserName = psUserName;
            inValue.psXMLMetaData = psXMLMetaData;
            inValue.psOutUserId = psOutUserId;
            Trisoft.ISHRemote.User25ServiceReference.CreateResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).Create(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutUserId = retVal.psOutUserId;
            return retVal.CreateResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.CreateResponse> CreateAsync(Trisoft.ISHRemote.User25ServiceReference.CreateRequest request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.UpdateResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.Update(Trisoft.ISHRemote.User25ServiceReference.UpdateRequest request)
        {
            return base.Channel.Update(request);
        }
        
        public string Update(ref string psAuthContext, string psUserId, string psXMLMetaData)
        {
            Trisoft.ISHRemote.User25ServiceReference.UpdateRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.UpdateRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserId = psUserId;
            inValue.psXMLMetaData = psXMLMetaData;
            Trisoft.ISHRemote.User25ServiceReference.UpdateResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).Update(inValue);
            psAuthContext = retVal.psAuthContext;
            return retVal.UpdateResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.UpdateResponse> UpdateAsync(Trisoft.ISHRemote.User25ServiceReference.UpdateRequest request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.DeleteResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.Delete(Trisoft.ISHRemote.User25ServiceReference.DeleteRequest request)
        {
            return base.Channel.Delete(request);
        }
        
        public string Delete(ref string psAuthContext, string psUserId)
        {
            Trisoft.ISHRemote.User25ServiceReference.DeleteRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.DeleteRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserId = psUserId;
            Trisoft.ISHRemote.User25ServiceReference.DeleteResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).Delete(inValue);
            psAuthContext = retVal.psAuthContext;
            return retVal.DeleteResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.DeleteResponse> DeleteAsync(Trisoft.ISHRemote.User25ServiceReference.DeleteRequest request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public string ChangePassword(string psApplicationName, string psUserName, string psOldPassword, string psNewPassword)
        {
            return base.Channel.ChangePassword(psApplicationName, psUserName, psOldPassword, psNewPassword);
        }
        
        public System.Threading.Tasks.Task<string> ChangePasswordAsync(string psApplicationName, string psUserName, string psOldPassword, string psNewPassword)
        {
            return base.Channel.ChangePasswordAsync(psApplicationName, psUserName, psOldPassword, psNewPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.SetPreferencesResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.SetPreferences(Trisoft.ISHRemote.User25ServiceReference.SetPreferencesRequest request)
        {
            return base.Channel.SetPreferences(request);
        }
        
        public string SetPreferences(ref string psAuthContext, string psUserId, string psXMLPreferences)
        {
            Trisoft.ISHRemote.User25ServiceReference.SetPreferencesRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.SetPreferencesRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserId = psUserId;
            inValue.psXMLPreferences = psXMLPreferences;
            Trisoft.ISHRemote.User25ServiceReference.SetPreferencesResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).SetPreferences(inValue);
            psAuthContext = retVal.psAuthContext;
            return retVal.SetPreferencesResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.SetPreferencesResponse> SetPreferencesAsync(Trisoft.ISHRemote.User25ServiceReference.SetPreferencesRequest request)
        {
            return base.Channel.SetPreferencesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.RetrievePreferences(Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesRequest request)
        {
            return base.Channel.RetrievePreferences(request);
        }
        
        public string RetrievePreferences(ref string psAuthContext, string psUserId, string[] pasSetNames, ref string psOutXMLPreferences)
        {
            Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserId = psUserId;
            inValue.pasSetNames = pasSetNames;
            inValue.psOutXMLPreferences = psOutXMLPreferences;
            Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).RetrievePreferences(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLPreferences = retVal.psOutXMLPreferences;
            return retVal.RetrievePreferencesResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesResponse> RetrievePreferencesAsync(Trisoft.ISHRemote.User25ServiceReference.RetrievePreferencesRequest request)
        {
            return base.Channel.RetrievePreferencesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.FindPreferencesResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.FindPreferences(Trisoft.ISHRemote.User25ServiceReference.FindPreferencesRequest request)
        {
            return base.Channel.FindPreferences(request);
        }
        
        public string FindPreferences(ref string psAuthContext, string psUserId, string psSetNameFilter, string psItemNameFilter, ref string psOutXMLPreferences)
        {
            Trisoft.ISHRemote.User25ServiceReference.FindPreferencesRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.FindPreferencesRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserId = psUserId;
            inValue.psSetNameFilter = psSetNameFilter;
            inValue.psItemNameFilter = psItemNameFilter;
            inValue.psOutXMLPreferences = psOutXMLPreferences;
            Trisoft.ISHRemote.User25ServiceReference.FindPreferencesResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).FindPreferences(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLPreferences = retVal.psOutXMLPreferences;
            return retVal.FindPreferencesResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.FindPreferencesResponse> FindPreferencesAsync(Trisoft.ISHRemote.User25ServiceReference.FindPreferencesRequest request)
        {
            return base.Channel.FindPreferencesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceResponse Trisoft.ISHRemote.User25ServiceReference.User25Soap.DeletePreference(Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceRequest request)
        {
            return base.Channel.DeletePreference(request);
        }
        
        public string DeletePreference(ref string psAuthContext, string psUserId, string psSetName, string psItemName)
        {
            Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceRequest inValue = new Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserId = psUserId;
            inValue.psSetName = psSetName;
            inValue.psItemName = psItemName;
            Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceResponse retVal = ((Trisoft.ISHRemote.User25ServiceReference.User25Soap)(this)).DeletePreference(inValue);
            psAuthContext = retVal.psAuthContext;
            return retVal.DeletePreferenceResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceResponse> DeletePreferenceAsync(Trisoft.ISHRemote.User25ServiceReference.DeletePreferenceRequest request)
        {
            return base.Channel.DeletePreferenceAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.User25Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.User25Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.User25Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://ish.example.com/ISHWS/user25.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.User25Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ish.example.com/ISHWS/user25.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            User25Soap,
            
            User25Soap12,
        }
    }
}

