//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trisoft.ISHRemote.MetadataBinding25ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", ConfigurationName="Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap")]
    internal interface MetadataBinding25Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5/ResolveIds", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsResponse ResolveIds(Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5/ResolveIds", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsResponse> ResolveIdsAsync(Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5/RetrieveTags", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsResponse RetrieveTags(Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5/RetrieveTags", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsResponse> RetrieveTagsAsync(Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5/RetrieveTagStructure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureResponse RetrieveTagStructure(Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5/RetrieveTagStructure", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureResponse> RetrieveTagStructureAsync(Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5/SmartTag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagResponse SmartTag(Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5/SmartTag", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagResponse> SmartTagAsync(Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResolveIds", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", IsWrapped=true)]
    internal partial class ResolveIdsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=1)]
        public string psXMLFieldTags;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=2)]
        public string psLanguage;
        
        public ResolveIdsRequest()
        {
        }
        
        public ResolveIdsRequest(string psAuthContext, string psXMLFieldTags, string psLanguage)
        {
            this.psAuthContext = psAuthContext;
            this.psXMLFieldTags = psXMLFieldTags;
            this.psLanguage = psLanguage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResolveIdsResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", IsWrapped=true)]
    internal partial class ResolveIdsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=0)]
        public string ResolveIdsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=2)]
        public string psOutXMLFieldTags;
        
        public ResolveIdsResponse()
        {
        }
        
        public ResolveIdsResponse(string ResolveIdsResult, string psAuthContext, string psOutXMLFieldTags)
        {
            this.ResolveIdsResult = ResolveIdsResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLFieldTags = psOutXMLFieldTags;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveTags", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", IsWrapped=true)]
    internal partial class RetrieveTagsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=1)]
        public string psFieldName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=2)]
        public string psFieldLevel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=3)]
        public string psInputFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=4)]
        public string psXMLFieldsFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=5)]
        public string psLanguage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=6)]
        public long plMaxTagsToReturn;
        
        public RetrieveTagsRequest()
        {
        }
        
        public RetrieveTagsRequest(string psAuthContext, string psFieldName, string psFieldLevel, string psInputFilter, string psXMLFieldsFilter, string psLanguage, long plMaxTagsToReturn)
        {
            this.psAuthContext = psAuthContext;
            this.psFieldName = psFieldName;
            this.psFieldLevel = psFieldLevel;
            this.psInputFilter = psInputFilter;
            this.psXMLFieldsFilter = psXMLFieldsFilter;
            this.psLanguage = psLanguage;
            this.plMaxTagsToReturn = plMaxTagsToReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveTagsResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", IsWrapped=true)]
    internal partial class RetrieveTagsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=0)]
        public string RetrieveTagsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=2)]
        public string psXMLFieldTags;
        
        public RetrieveTagsResponse()
        {
        }
        
        public RetrieveTagsResponse(string RetrieveTagsResult, string psAuthContext, string psXMLFieldTags)
        {
            this.RetrieveTagsResult = RetrieveTagsResult;
            this.psAuthContext = psAuthContext;
            this.psXMLFieldTags = psXMLFieldTags;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveTagStructure", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", IsWrapped=true)]
    internal partial class RetrieveTagStructureRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=1)]
        public string psFieldName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=2)]
        public string psFieldLevel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=3)]
        public string psXMLFieldsFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=4)]
        public string psLanguage;
        
        public RetrieveTagStructureRequest()
        {
        }
        
        public RetrieveTagStructureRequest(string psAuthContext, string psFieldName, string psFieldLevel, string psXMLFieldsFilter, string psLanguage)
        {
            this.psAuthContext = psAuthContext;
            this.psFieldName = psFieldName;
            this.psFieldLevel = psFieldLevel;
            this.psXMLFieldsFilter = psXMLFieldsFilter;
            this.psLanguage = psLanguage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveTagStructureResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", IsWrapped=true)]
    internal partial class RetrieveTagStructureResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=0)]
        public string RetrieveTagStructureResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=2)]
        public string psXMLFieldTags;
        
        public RetrieveTagStructureResponse()
        {
        }
        
        public RetrieveTagStructureResponse(string RetrieveTagStructureResult, string psAuthContext, string psXMLFieldTags)
        {
            this.RetrieveTagStructureResult = RetrieveTagStructureResult;
            this.psAuthContext = psAuthContext;
            this.psXMLFieldTags = psXMLFieldTags;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmartTag", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", IsWrapped=true)]
    internal partial class SmartTagRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=1)]
        public string psXMLFieldTags;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=2)]
        public string psLanguage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=3)]
        public string psDataLanguage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=4)]
        public string psEdt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pbData;
        
        public SmartTagRequest()
        {
        }
        
        public SmartTagRequest(string psAuthContext, string psXMLFieldTags, string psLanguage, string psDataLanguage, string psEdt, byte[] pbData)
        {
            this.psAuthContext = psAuthContext;
            this.psXMLFieldTags = psXMLFieldTags;
            this.psLanguage = psLanguage;
            this.psDataLanguage = psDataLanguage;
            this.psEdt = psEdt;
            this.pbData = pbData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SmartTagResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", IsWrapped=true)]
    internal partial class SmartTagResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=0)]
        public string SmartTagResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:MetadataBinding:2.5", Order=2)]
        public string psOutXMLFieldTags;
        
        public SmartTagResponse()
        {
        }
        
        public SmartTagResponse(string SmartTagResult, string psAuthContext, string psOutXMLFieldTags)
        {
            this.SmartTagResult = SmartTagResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLFieldTags = psOutXMLFieldTags;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface MetadataBinding25SoapChannel : Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class MetadataBinding25SoapClient : System.ServiceModel.ClientBase<Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap>, Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MetadataBinding25SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MetadataBinding25SoapClient.GetBindingForEndpoint(endpointConfiguration), MetadataBinding25SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetadataBinding25SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MetadataBinding25SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetadataBinding25SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MetadataBinding25SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MetadataBinding25SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsResponse Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap.ResolveIds(Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsRequest request)
        {
            return base.Channel.ResolveIds(request);
        }
        
        public string ResolveIds(ref string psAuthContext, string psXMLFieldTags, string psLanguage, out string psOutXMLFieldTags)
        {
            Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsRequest inValue = new Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psXMLFieldTags = psXMLFieldTags;
            inValue.psLanguage = psLanguage;
            Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsResponse retVal = ((Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap)(this)).ResolveIds(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLFieldTags = retVal.psOutXMLFieldTags;
            return retVal.ResolveIdsResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsResponse> ResolveIdsAsync(Trisoft.ISHRemote.MetadataBinding25ServiceReference.ResolveIdsRequest request)
        {
            return base.Channel.ResolveIdsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsResponse Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap.RetrieveTags(Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsRequest request)
        {
            return base.Channel.RetrieveTags(request);
        }
        
        public string RetrieveTags(ref string psAuthContext, string psFieldName, string psFieldLevel, string psInputFilter, string psXMLFieldsFilter, string psLanguage, long plMaxTagsToReturn, out string psXMLFieldTags)
        {
            Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsRequest inValue = new Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psFieldName = psFieldName;
            inValue.psFieldLevel = psFieldLevel;
            inValue.psInputFilter = psInputFilter;
            inValue.psXMLFieldsFilter = psXMLFieldsFilter;
            inValue.psLanguage = psLanguage;
            inValue.plMaxTagsToReturn = plMaxTagsToReturn;
            Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsResponse retVal = ((Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap)(this)).RetrieveTags(inValue);
            psAuthContext = retVal.psAuthContext;
            psXMLFieldTags = retVal.psXMLFieldTags;
            return retVal.RetrieveTagsResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsResponse> RetrieveTagsAsync(Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagsRequest request)
        {
            return base.Channel.RetrieveTagsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureResponse Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap.RetrieveTagStructure(Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureRequest request)
        {
            return base.Channel.RetrieveTagStructure(request);
        }
        
        public string RetrieveTagStructure(ref string psAuthContext, string psFieldName, string psFieldLevel, string psXMLFieldsFilter, string psLanguage, out string psXMLFieldTags)
        {
            Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureRequest inValue = new Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psFieldName = psFieldName;
            inValue.psFieldLevel = psFieldLevel;
            inValue.psXMLFieldsFilter = psXMLFieldsFilter;
            inValue.psLanguage = psLanguage;
            Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureResponse retVal = ((Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap)(this)).RetrieveTagStructure(inValue);
            psAuthContext = retVal.psAuthContext;
            psXMLFieldTags = retVal.psXMLFieldTags;
            return retVal.RetrieveTagStructureResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureResponse> RetrieveTagStructureAsync(Trisoft.ISHRemote.MetadataBinding25ServiceReference.RetrieveTagStructureRequest request)
        {
            return base.Channel.RetrieveTagStructureAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagResponse Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap.SmartTag(Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagRequest request)
        {
            return base.Channel.SmartTag(request);
        }
        
        public string SmartTag(ref string psAuthContext, string psXMLFieldTags, string psLanguage, string psDataLanguage, string psEdt, byte[] pbData, out string psOutXMLFieldTags)
        {
            Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagRequest inValue = new Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psXMLFieldTags = psXMLFieldTags;
            inValue.psLanguage = psLanguage;
            inValue.psDataLanguage = psDataLanguage;
            inValue.psEdt = psEdt;
            inValue.pbData = pbData;
            Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagResponse retVal = ((Trisoft.ISHRemote.MetadataBinding25ServiceReference.MetadataBinding25Soap)(this)).SmartTag(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLFieldTags = retVal.psOutXMLFieldTags;
            return retVal.SmartTagResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagResponse> SmartTagAsync(Trisoft.ISHRemote.MetadataBinding25ServiceReference.SmartTagRequest request)
        {
            return base.Channel.SmartTagAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MetadataBinding25Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MetadataBinding25Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MetadataBinding25Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://ish.example.com/ISHWS/metadatabinding25.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MetadataBinding25Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ish.example.com/ISHWS/metadatabinding25.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MetadataBinding25Soap,
            
            MetadataBinding25Soap12,
        }
    }
}

