//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trisoft.ISHRemote.UserGroup25ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", ConfigurationName="Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap")]
    internal interface UserGroup25Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/GetMetaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataResponse GetMetaData(Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/GetMetaData", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataResponse> GetMetaDataAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/RetrieveMetaData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataResponse RetrieveMetaData(Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/RetrieveMetaData", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataResponse> RetrieveMetaDataAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/Find", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.FindResponse Find(Trisoft.ISHRemote.UserGroup25ServiceReference.FindRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/Find", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.FindResponse> FindAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.CreateResponse Create(Trisoft.ISHRemote.UserGroup25ServiceReference.CreateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.CreateResponse> CreateAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateResponse Update(Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateResponse> UpdateAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteResponse Delete(Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteResponse> DeleteAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMetaData", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class GetMetaDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string psUserGroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=2)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=3)]
        public string psOutXMLObjList;
        
        public GetMetaDataRequest()
        {
        }
        
        public GetMetaDataRequest(string psAuthContext, string psUserGroupId, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.psUserGroupId = psUserGroupId;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMetaDataResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class GetMetaDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string GetMetaDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public GetMetaDataResponse()
        {
        }
        
        public GetMetaDataResponse(string GetMetaDataResult, string psAuthContext, string psOutXMLObjList)
        {
            this.GetMetaDataResult = GetMetaDataResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5")]
    public enum eActivityFilter
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Inactive,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveMetaData", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class RetrieveMetaDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string[] pasUserGroupIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=2)]
        public Trisoft.ISHRemote.UserGroup25ServiceReference.eActivityFilter peActivityFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=3)]
        public string psXMLMetadataFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=4)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=5)]
        public string psOutXMLObjList;
        
        public RetrieveMetaDataRequest()
        {
        }
        
        public RetrieveMetaDataRequest(string psAuthContext, string[] pasUserGroupIds, Trisoft.ISHRemote.UserGroup25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.pasUserGroupIds = pasUserGroupIds;
            this.peActivityFilter = peActivityFilter;
            this.psXMLMetadataFilter = psXMLMetadataFilter;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RetrieveMetaDataResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class RetrieveMetaDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string RetrieveMetaDataResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public RetrieveMetaDataResponse()
        {
        }
        
        public RetrieveMetaDataResponse(string RetrieveMetaDataResult, string psAuthContext, string psOutXMLObjList)
        {
            this.RetrieveMetaDataResult = RetrieveMetaDataResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Find", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class FindRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public Trisoft.ISHRemote.UserGroup25ServiceReference.eActivityFilter peActivityFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=2)]
        public string psXMLMetadataFilter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=3)]
        public string psXMLRequestedMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=4)]
        public string psOutXMLObjList;
        
        public FindRequest()
        {
        }
        
        public FindRequest(string psAuthContext, Trisoft.ISHRemote.UserGroup25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, string psOutXMLObjList)
        {
            this.psAuthContext = psAuthContext;
            this.peActivityFilter = peActivityFilter;
            this.psXMLMetadataFilter = psXMLMetadataFilter;
            this.psXMLRequestedMetaData = psXMLRequestedMetaData;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class FindResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string FindResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=2)]
        public string psOutXMLObjList;
        
        public FindResponse()
        {
        }
        
        public FindResponse(string FindResult, string psAuthContext, string psOutXMLObjList)
        {
            this.FindResult = FindResult;
            this.psAuthContext = psAuthContext;
            this.psOutXMLObjList = psOutXMLObjList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class CreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string psUserGroupName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=2)]
        public string psXMLMetaData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=3)]
        public string psOutUserGroupId;
        
        public CreateRequest()
        {
        }
        
        public CreateRequest(string psAuthContext, string psUserGroupName, string psXMLMetaData, string psOutUserGroupId)
        {
            this.psAuthContext = psAuthContext;
            this.psUserGroupName = psUserGroupName;
            this.psXMLMetaData = psXMLMetaData;
            this.psOutUserGroupId = psOutUserGroupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class CreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string CreateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=2)]
        public string psOutUserGroupId;
        
        public CreateResponse()
        {
        }
        
        public CreateResponse(string CreateResult, string psAuthContext, string psOutUserGroupId)
        {
            this.CreateResult = CreateResult;
            this.psAuthContext = psAuthContext;
            this.psOutUserGroupId = psOutUserGroupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string psUserGroupId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=2)]
        public string psXMLMetaData;
        
        public UpdateRequest()
        {
        }
        
        public UpdateRequest(string psAuthContext, string psUserGroupId, string psXMLMetaData)
        {
            this.psAuthContext = psAuthContext;
            this.psUserGroupId = psUserGroupId;
            this.psXMLMetaData = psXMLMetaData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string UpdateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string psAuthContext;
        
        public UpdateResponse()
        {
        }
        
        public UpdateResponse(string UpdateResult, string psAuthContext)
        {
            this.UpdateResult = UpdateResult;
            this.psAuthContext = psAuthContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class DeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string psAuthContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string psUserGroupId;
        
        public DeleteRequest()
        {
        }
        
        public DeleteRequest(string psAuthContext, string psUserGroupId)
        {
            this.psAuthContext = psAuthContext;
            this.psUserGroupId = psUserGroupId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResponse", WrapperNamespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", IsWrapped=true)]
    internal partial class DeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=0)]
        public string DeleteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:trisoft.be:WebServices:InfoShare:UserGroup:2.5", Order=1)]
        public string psAuthContext;
        
        public DeleteResponse()
        {
        }
        
        public DeleteResponse(string DeleteResult, string psAuthContext)
        {
            this.DeleteResult = DeleteResult;
            this.psAuthContext = psAuthContext;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface UserGroup25SoapChannel : Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class UserGroup25SoapClient : System.ServiceModel.ClientBase<Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap>, Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UserGroup25SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(UserGroup25SoapClient.GetBindingForEndpoint(endpointConfiguration), UserGroup25SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserGroup25SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UserGroup25SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserGroup25SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UserGroup25SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UserGroup25SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataResponse Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap.GetMetaData(Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataRequest request)
        {
            return base.Channel.GetMetaData(request);
        }
        
        public string GetMetaData(ref string psAuthContext, string psUserGroupId, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataRequest inValue = new Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserGroupId = psUserGroupId;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataResponse retVal = ((Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap)(this)).GetMetaData(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.GetMetaDataResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataResponse> GetMetaDataAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.GetMetaDataRequest request)
        {
            return base.Channel.GetMetaDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataResponse Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap.RetrieveMetaData(Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataRequest request)
        {
            return base.Channel.RetrieveMetaData(request);
        }
        
        public string RetrieveMetaData(ref string psAuthContext, string[] pasUserGroupIds, Trisoft.ISHRemote.UserGroup25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataRequest inValue = new Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.pasUserGroupIds = pasUserGroupIds;
            inValue.peActivityFilter = peActivityFilter;
            inValue.psXMLMetadataFilter = psXMLMetadataFilter;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataResponse retVal = ((Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap)(this)).RetrieveMetaData(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.RetrieveMetaDataResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataResponse> RetrieveMetaDataAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.RetrieveMetaDataRequest request)
        {
            return base.Channel.RetrieveMetaDataAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.FindResponse Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap.Find(Trisoft.ISHRemote.UserGroup25ServiceReference.FindRequest request)
        {
            return base.Channel.Find(request);
        }
        
        public string Find(ref string psAuthContext, Trisoft.ISHRemote.UserGroup25ServiceReference.eActivityFilter peActivityFilter, string psXMLMetadataFilter, string psXMLRequestedMetaData, ref string psOutXMLObjList)
        {
            Trisoft.ISHRemote.UserGroup25ServiceReference.FindRequest inValue = new Trisoft.ISHRemote.UserGroup25ServiceReference.FindRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.peActivityFilter = peActivityFilter;
            inValue.psXMLMetadataFilter = psXMLMetadataFilter;
            inValue.psXMLRequestedMetaData = psXMLRequestedMetaData;
            inValue.psOutXMLObjList = psOutXMLObjList;
            Trisoft.ISHRemote.UserGroup25ServiceReference.FindResponse retVal = ((Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap)(this)).Find(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutXMLObjList = retVal.psOutXMLObjList;
            return retVal.FindResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.FindResponse> FindAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.FindRequest request)
        {
            return base.Channel.FindAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.CreateResponse Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap.Create(Trisoft.ISHRemote.UserGroup25ServiceReference.CreateRequest request)
        {
            return base.Channel.Create(request);
        }
        
        public string Create(ref string psAuthContext, string psUserGroupName, string psXMLMetaData, ref string psOutUserGroupId)
        {
            Trisoft.ISHRemote.UserGroup25ServiceReference.CreateRequest inValue = new Trisoft.ISHRemote.UserGroup25ServiceReference.CreateRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserGroupName = psUserGroupName;
            inValue.psXMLMetaData = psXMLMetaData;
            inValue.psOutUserGroupId = psOutUserGroupId;
            Trisoft.ISHRemote.UserGroup25ServiceReference.CreateResponse retVal = ((Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap)(this)).Create(inValue);
            psAuthContext = retVal.psAuthContext;
            psOutUserGroupId = retVal.psOutUserGroupId;
            return retVal.CreateResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.CreateResponse> CreateAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.CreateRequest request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateResponse Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap.Update(Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateRequest request)
        {
            return base.Channel.Update(request);
        }
        
        public string Update(ref string psAuthContext, string psUserGroupId, string psXMLMetaData)
        {
            Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateRequest inValue = new Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserGroupId = psUserGroupId;
            inValue.psXMLMetaData = psXMLMetaData;
            Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateResponse retVal = ((Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap)(this)).Update(inValue);
            psAuthContext = retVal.psAuthContext;
            return retVal.UpdateResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateResponse> UpdateAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.UpdateRequest request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteResponse Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap.Delete(Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteRequest request)
        {
            return base.Channel.Delete(request);
        }
        
        public string Delete(ref string psAuthContext, string psUserGroupId)
        {
            Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteRequest inValue = new Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteRequest();
            inValue.psAuthContext = psAuthContext;
            inValue.psUserGroupId = psUserGroupId;
            Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteResponse retVal = ((Trisoft.ISHRemote.UserGroup25ServiceReference.UserGroup25Soap)(this)).Delete(inValue);
            psAuthContext = retVal.psAuthContext;
            return retVal.DeleteResult;
        }
        
        public System.Threading.Tasks.Task<Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteResponse> DeleteAsync(Trisoft.ISHRemote.UserGroup25ServiceReference.DeleteRequest request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserGroup25Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.UserGroup25Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UserGroup25Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://ish.example.com/ISHWS/usergroup25.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.UserGroup25Soap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ish.example.com/ISHWS/usergroup25.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            UserGroup25Soap,
            
            UserGroup25Soap12,
        }
    }
}

