name: Continuous Integration

on:
  push:
    branches: [ 115-Milestone-Enable-PowerShell-Core ]
  pull_request:
    branches: [ 115-Milestone-Enable-PowerShell-Core ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore project and dependencies
      run: dotnet restore Source/ISHRemote/ISHRemote.sln
    
    - name: Build Solution
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet build --no-restore --no-incremental --configuration release Source/ISHRemote/ISHRemote.sln
    
    - name: Setup PowerShell PSScriptAnalyzer
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module PSScriptAnalyzer -ErrorAction Stop
    
    - name: Lint with PSScriptAnalyzer
      shell: pwsh
      run: |
        Invoke-ScriptAnalyzer -Path Source/ISHRemote/Trisoft.ISHRemote/Scripts -Recurse -Outvariable issues
        $errors   = $issues.Where({$_.Severity -eq 'Error'})
        $warnings = $issues.Where({$_.Severity -eq 'Warning'})
        if ($errors) {
            Write-Warning "There were $($errors.Count) errors and $($warnings.Count) warnings total."
        } else {
            Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
        }
    
    - name: Archive ISHRemote module
      uses: actions/upload-artifact@v2
      with: 
        name: ISHRemote-module
        path: Source/ISHRemote/Trisoft.ISHRemote/bin/Release/*.nupkg

    - name: Pester Test Cmdlets on Windows using PowerShell 7.x
      shell: pwsh
      env:
        ISH_BASE_URL: ${{ secrets.ISH_BASE_URL }}
        ISH_USER_NAME: ${{ secrets.ISH_USER_NAME }}
        ISH_PASSWORD: ${{ secrets.ISH_PASSWORD }}
      run: Invoke-Pester -Path Source/ISHRemote/Trisoft.ISHRemote/Cmdlets/ -Output Detailed -Passthru | Export-CliXml -Path Cmdlets.Pester.Tests.xml
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Cmdlets pester test results
        path: Cmdlets.Pester.Tests.xml
      if: ${{ always() }}
