name: Continuous Integration

on:
  push:
    branches: [ 115-Milestone-Enable-PowerShell-Core ]
  pull_request:
    branches: [ 115-Milestone-Enable-PowerShell-Core ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore Source/ISHRemote/ISHRemote.sln
    
    - name: Build
      run: dotnet build --no-restore --no-incremental --configuration release Source/ISHRemote/ISHRemote.sln
    
    - name: Install PSScriptAnalyzer module
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module PSScriptAnalyzer -ErrorAction Stop
    
    - name: Lint with PSScriptAnalyzer
      shell: pwsh
      run: |
        Invoke-ScriptAnalyzer -Path Source/ISHRemote/Trisoft.ISHRemote/Scripts -Recurse -Outvariable issues
        $errors   = $issues.Where({$_.Severity -eq 'Error'})
        $warnings = $issues.Where({$_.Severity -eq 'Warning'})
        if ($errors) {
            Write-Warning "There were $($errors.Count) errors and $($warnings.Count) warnings total."
        } else {
            Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
        }
    
    - name: Archive ISHRemote module
      uses: actions/upload-artifact@v2
      with: 
        name: ISHRemote-module
        path: Source/ISHRemote/Trisoft.ISHRemote/bin/Release/*.nupkg

    - name: Test CmdLets with Pester
      shell: pwsh
      run: Invoke-Pester Source/ISHRemote/Trisoft.ISHRemote/Cmdlets/Session/NewIshSession.Tests.ps1 -Passthru | Export-CliXml -Path NewIshSession.Pester.Tests.xml
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: New-IshSession pester test results
        path: NewIshSession.Pester.Tests.xml

#    if: ${{ always() }}